import { demos } from "@/data/demos";
import Header from "@/components/Header";
import DemoCard from "@/components/DemoCard";
import FilmGrain from "@/components/FilmGrain";

export default function Home() {
  return (
    <>
      <FilmGrain />
      <Header />
      <main className="mx-auto max-w-6xl px-6 pb-24">
        {/* Hero */}
        <section className="pb-16 pt-24 text-center">
          <h1 className="animate-fade-up font-heading text-5xl tracking-tight text-[#e8e0d4] md:text-7xl">
            Cinematic UI
          </h1>
          <p className="animate-fade-up animation-delay-100 mx-auto mt-4 max-w-lg font-body text-lg text-[#7a7068]">
            Six websites. Six directors. One design language.
          </p>
          <p className="animate-fade-up animation-delay-200 mx-auto mt-6 max-w-2xl font-body text-sm leading-relaxed text-[#5a534d]">
            Each site is generated from a single prompt using the{" "}
            <span className="text-[#c4a46a]">Cinematic UI</span> Claude Skill
            &mdash; translating a film&apos;s visual grammar into web design
            through director-driven art direction, storyboard-first layout, and
            cinematic motion.
          </p>
        </section>

        {/* Demo grid */}
        <section className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">
          {demos.map((demo, i) => (
            <div
              key={demo.slug}
              className="animate-fade-up"
              style={{ animationDelay: `${0.15 + i * 0.08}s` }}
            >
              <DemoCard demo={demo} />
            </div>
          ))}
        </section>

        {/* Footer */}
        <footer className="mt-24 border-t border-white/[0.06] pt-8 text-center">
          <p className="font-body text-xs text-[#5a534d]">
            Built with Next.js. Demos generated by the Cinematic UI Claude
            Skill.
          </p>
          <p className="mt-1 font-body text-xs text-[#3a3530]">
            Each demo is a static HTML/CSS/JS site &mdash; no frameworks, pure
            web standards.
          </p>
        </footer>
      </main>
    </>
  );
}
